# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'BillBoard' do
pod 'Venmo-iOS-SDK', '~>1.3'
pod 'Spring'
# 现在默认 swift 2.0会爆炸  不要改回来
pod 'Alamofire', '~>1.3'
pod 'SwiftyJSON'
pod 'TextFieldEffects'
pod 'MJRefresh'
pod 'DZNEmptyDataSet'
pod 'JTSImageViewController'
pod 'SDWebImage'
pod 'SnapKit'
pod 'WYInteractiveTransitions'
pod 'ZFRippleButton'
pod 'CRToast'
end

target 'BillBoardTests' do

end

use_frameworks!
