# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'BillBoard' do
pod 'Venmo-iOS-SDK', '~>1.3'
pod 'Spring'
pod 'Alamofire', '~> 1.3'
pod 'SwiftyJSON'
end

target 'BillBoardTests' do

end

use_frameworks!
